# Generated by Django 5.0.1 on 2026-03-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamechallenge'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='move',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='move',
            name='game',
        ),
        migrations.RemoveField(
            model_name='game',
            name='black_time_left',
        ),
        migrations.RemoveField(
            model_name='game',
            name='current_fen',
        ),
        migrations.RemoveField(
            model_name='game',
            name='current_turn',
        ),
        migrations.RemoveField(
            model_name='game',
            name='move_count',
        ),
        migrations.RemoveField(
            model_name='game',
            name='spectator_count',
        ),
        migrations.RemoveField(
            model_name='game',
            name='white_time_left',
        ),
        migrations.AddField(
            model_name='game',
            name='final_fen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='move_history',
            field=models.JSONField(blank=True, default=list, help_text='List of UCI moves saved at game end.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pgn',
            field=models.TextField(blank=True, help_text='Generated and saved only when the game concludes.'),
        ),
        migrations.DeleteModel(
            name='MatchmakingQueue',
        ),
        migrations.DeleteModel(
            name='Move',
        ),
    ]
